import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Administrador',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Usuario',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Remeras',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'Remera de alta calidad',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Zapatillas',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'Prenda de alta calidad',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pantalones',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'Producto de alta calidad',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Abrigos',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'Producto de alta calidad',
    },
  ],
  featuredItems: [
    {
      id: 1,
      title: '¡Nueva colección de verano!',
      description: 'Descubrí los nuevos estilos para la temporada 2025.',
      imageUrl: '/images/coleccion-verano.jpg',
      link: '/coleccion/verano',
      active: true,
    },
    {
      id: 2,
      title: 'Semana de descuentos',
      description: 'Hasta 50% de descuento en productos seleccionados.',
      imageUrl: '/images/ofertas-semana.jpg',
      link: '/ofertas',
      active: true,
    },
    {
      id: 3,
      title: 'Tienda online renovada',
      description: 'Estrenamos diseño, ¡mucha más facilidad de navegación!',
      imageUrl: '/images/tienda-renovada.jpg',
      link: '/nueva-tienda',
      active: true,
    },
  ],
};

export default data;
